<StartupScreen>
    name: 'StartupScreen'
    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    Image
        id: img_logo
        allow_strech: True
        keep_ratio: False
        source: './static/images/applogo.png'
        size_hint_y: .5
        size_hint_x: .8
        pos_hint : {'center_x': .5, 'center_y': .5}

